USE UASU_Finance_01;
GO

-- ============================================
-- Users
-- Login credentials for the web app, one row per
-- Official who needs to sign in (Chairman, Chapter
-- Secretary, Treasurer, etc.). Kept separate from
-- Ref_Officials so officer records stay clean even
-- as login/auth details change.
-- ============================================
CREATE TABLE Users (
    OfficialID NVARCHAR(20) PRIMARY KEY
        FOREIGN KEY REFERENCES Ref_Officials(OfficialID),

    Username NVARCHAR(100) NOT NULL UNIQUE,   -- e.g. an email or short login name
    PasswordHash NVARCHAR(255) NOT NULL,      -- BCrypt hash, never store plaintext

    -- Forces a password change on first sign-in. Defaults to 1 so every
    -- freshly-seeded login (see the INSERTs below) must be changed before
    -- the officer can use anything else in the app; cleared automatically
    -- once they set their own password.
    MustChangePassword BIT NOT NULL DEFAULT 1,

    IsActive BIT NOT NULL DEFAULT 1,
    LastLogin DATETIME NULL,
    Created_At DATETIME NOT NULL DEFAULT GETDATE()
);
GO

-- ------------------------------------------------------------------
-- Guard rail: a login can only be created/updated for an official who
-- is currently serving (IsCurrent = 1). AuthService also joins on
-- IsCurrent = 1 at sign-in time, so an officer leaving office (flag
-- flipped to 0) loses access even without touching this table.
-- ------------------------------------------------------------------
CREATE TRIGGER trg_Users_ValidateOfficial
ON Users
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted i
        INNER JOIN Ref_Officials o ON o.OfficialID = i.OfficialID
        WHERE o.IsCurrent = 0
    )
    BEGIN
        RAISERROR('Cannot create or update a login for an official who is not currently serving.',16,1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
END;
GO

-- ------------------------------------------------------------------
-- Example: create a login for the Chairman and Chapter Secretary.
-- Replace the placeholder hash below with a real BCrypt hash
-- generated by the app (see README.md) before running this for real
-- — do not insert plaintext passwords.
-- ------------------------------------------------------------------
-- INSERT INTO Users (OfficialID, Username, PasswordHash)
-- SELECT OfficialID, 'chairman@uasu.example', '<bcrypt-hash-here>'
-- FROM Ref_Officials WHERE Role = 'Chairman' AND IsCurrent = 1;

-- INSERT INTO Users (OfficialID, Username, PasswordHash)
-- SELECT OfficialID, 'secretary@uasu.example', '<bcrypt-hash-here>'
-- FROM Ref_Officials WHERE Role = 'Chapter Secretary' AND IsCurrent = 1;
